/**
 * Drawing an Uno card.
 *
 * The same arrangement as the playing-card deck: one sprite sheet, and a card
 * is a div with the right cell of it scrolled into view. Thirteen faces across
 * — nought to nine, then Skip, Reverse and Draw Two — and one row per colour,
 * with the wilds and the back on the row after them.
 *
 * The sheet is generated by `scripts/build-uno-sheet.py` and committed. It is
 * built rather than drawn by hand because a deck needs all fifty-four faces
 * and a card the game believes is a four when the picture says seven is a bug
 * nobody would think to look for.
 */
import React from 'react';

import sheet from '../assets/uno.png';
import { COLOURS, describe } from './uno';
import type { UnoCard } from './uno';
import { cn } from './utils';

const COLS = 13;
const ROWS = 5;

/** One cell, in the sheet's own pixels. */
const CELL_W = 104;
const CELL_H = 148;
export const UNO_RATIO = CELL_H / CELL_W;
export const unoHeight = (width: number): number => Math.round(width * UNO_RATIO);

/** Where a card sits on the sheet. */
function cellOf(card: UnoCard): { col: number; row: number } {
  if (card.kind === 'wild') return { col: 0, row: 4 };
  if (card.kind === 'wild4') return { col: 1, row: 4 };

  const row = COLOURS.indexOf(card.colour);
  if (card.kind === 'number') return { col: card.n, row };
  if (card.kind === 'skip') return { col: 10, row };
  if (card.kind === 'reverse') return { col: 11, row };
  return { col: 12, row };
}

const BACK = { col: 2, row: 4 };

function Sprite({
  col,
  row,
  width,
  fill,
  label,
  className,
  style,
}: {
  col: number;
  row: number;
  width: number;
  fill?: boolean;
  label?: string;
  className?: string;
  style?: React.CSSProperties;
}) {
  const height = unoHeight(width);

  // Percentages address the sheet the same way pixels do, as long as the
  // position is scaled by the number of cells minus one — see `pixelcards`.
  const placement: React.CSSProperties = fill
    ? {
        width: '100%',
        height: '100%',
        backgroundSize: `${COLS * 100}% ${ROWS * 100}%`,
        backgroundPosition: `${(col / (COLS - 1)) * 100}% ${(row / (ROWS - 1)) * 100}%`,
      }
    : {
        width,
        height,
        backgroundSize: `${COLS * width}px ${ROWS * height}px`,
        backgroundPosition: `${-col * width}px ${-row * height}px`,
      };

  return (
    <span
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={label ? undefined : true}
      className={cn('block shrink-0', className)}
      style={{
        ...placement,
        backgroundImage: `url(${sheet})`,
        backgroundRepeat: 'no-repeat',
        imageRendering: 'pixelated',
        ...style,
      }}
    />
  );
}

export function UnoFace({
  card,
  width = 62,
  fill,
  labelled = true,
  className,
  style,
}: {
  card: UnoCard;
  width?: number;
  fill?: boolean;
  labelled?: boolean;
  className?: string;
  style?: React.CSSProperties;
}) {
  const { col, row } = cellOf(card);
  return (
    <Sprite
      col={col}
      row={row}
      width={width}
      fill={fill}
      label={labelled ? describe(card) : undefined}
      className={className}
      style={style}
    />
  );
}

export function UnoBack({
  width = 62,
  fill,
  className,
  style,
}: {
  width?: number;
  fill?: boolean;
  className?: string;
  style?: React.CSSProperties;
}) {
  return (
    <Sprite
      col={BACK.col}
      row={BACK.row}
      width={width}
      fill={fill}
      className={className}
      style={style}
    />
  );
}
